require-stack-version: ">= 1.0.3"
resolver: lts-5.2
extra-deps:
- pandoc-crossref-0.1.6.5
- data-accessor-transformers-0.2.1.7
packages:
- location: https://github.com/da-x/fancydiff/archive/10bbc539ed2a32e885d2c3b86c5ca7c950a1114b.zip
  extra-dep: true
- location: https://github.com/da-x/gitlib/archive/5b338169a2618337a60aaf17e2ab56a2654b1244.zip
  extra-dep: true
  subdirs:
  - gitlib
  - gitlib-libgit2
  - hlibgit2
- .
